.TH SECRET 1

.SH NAME
secret \- Send encrypted file via ICMP packets

.SH SYNOPSIS
.B secret \fB\-s\fR \fI<ip|hostname>\fR \fB\-r\fR \fI<file>\fR [\fB\-l\fR]

.SH DESCRIPTION
.B secret
Program encrypt file and send this file with ICMP ECHO packtes on other site program waiting in listen mode for packets and deecrypt it and save it to file

.SH OPTIONS

.TP
.BR \-s
ip address or hostname of destination

.TP
.BR \-l
active listen mode

.TP
.BR \-r
file for send or recive
